// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed_follows.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addFeedFollow = `-- name: AddFeedFollow :one
WITH insert_feed_follow AS (
        INSERT INTO feed_follows (user_id, feed_id) VALUES ($1, $2) RETURNING id, user_id, feed_id, created_at, updated_at
)
SELECT ff.id, ff.user_id, ff.feed_id, ff.created_at, ff.updated_at, u.name AS user_name, f.name AS feed_name FROM insert_feed_follow ff JOIN users u ON ff.user_id = u.id JOIN feed f ON f.id = ff.feed_id
`

type AddFeedFollowParams struct {
	UserID uuid.NullUUID
	FeedID uuid.NullUUID
}

type AddFeedFollowRow struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	FeedID    uuid.NullUUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	UserName  string
	FeedName  string
}

func (q *Queries) AddFeedFollow(ctx context.Context, arg AddFeedFollowParams) (AddFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, addFeedFollow, arg.UserID, arg.FeedID)
	var i AddFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.FeedName,
	)
	return i, err
}
